#!/bin/bash

#GRAB PARAMETERS
OLD_USER=$1
NEW_USER=$2
NEW_SSH_PORT=$3
REVERT_TIMER=$4
REVERT_TIMER=$((REVERT_TIMER*60))

#PATHS
PATH_INITPI=$(readlink -f "$0")
PATH_INITPI_DIR=$(dirname "$PATH_INITPI")
PATH_INITPI_PATHS=$PATH_INITPI_DIR/paths
source $PATH_INITPI_PATHS

#WAIT UNTIL rc.local FINISHES AND RESTORE IT TO IT'S ORIGINAL STATE
while pidof -x rc.local > /dev/null
do
	sleep 1
done
cp $PATH_RCLOCAL_BACKUP $PATH_RCLOCAL

#WAIT FOR SYSTEM TO BE UP AND RUNNING
systemctl is-system-running --wait

#LOCK OLD USER
if [[ $OLD_USER != $NEW_USER ]]
then
	chage -E 0 $OLD_USER
fi

#ENABLE FIREWALL
ufw limit $NEW_SSH_PORT/tcp
ufw enable

#ENABLE FAIL2BAN
cp $PATH_FAIL2BAN_CONF $PATH_FAIL2BAN_LOCAL

#UNLOCK NEW USER
chage -E -1 $NEW_USER

#START SSH SERVER
systemctl enable ssh
systemctl start ssh

#WAIT FOR SSH CONNECTION
while [[ -z "$CONNECTION" ]] && [[ $SECONDS -le $REVERT_TIMER ]]
do
	CONNECTION="$(who | grep $NEW_USER)"
done

#UNLOCK OLD USER REGARDLESS OF A CONNECTION
chage -E -1 $OLD_USER

#IF A CONNECTION WAS MADE...
if [[ -n "$CONNECTION" ]]
then
	#IF THERE IS A NEW USER, DELETE THE OLD USER
	if [[ $OLD_USER != $NEW_USER ]]
	then
		sudo deluser -remove-home $OLD_USER
		sed -i "/^$OLD_USER /d" $PATH_SUDO_PASSWORD_CONF
	fi
#IF NO CONNECTION WAS MADE...
else
	#IF THERE IS A NEW USER, DELETE IT
	#IF THERE IS NOT, REVERT TO DEFAULT PASSWORD
        if [[ $OLD_USER == $NEW_USER ]]
        then
		echo $OLD_USER:raspberry | chpasswd
	else
		sudo deluser -remove-home $NEW_USER
		rm -r $PATH_USER_SSH
        fi
	#REVERT SYSTEM
	cp $PATH_WPA_CONF_BACKUP $PATH_WPA_CONF
	wpa_cli -i wlan0 reconfigure
	cp $PATH_SUDO_PASSWORD_CONF_BACKUP $PATH_SUDO_PASSWORD_CONF
	cp $PATH_SSH_CONF_BACKUP $PATH_SSH_CONF
	systemctl stop ssh
	systemctl disable ssh
	rm $PATH_FAIL2BAN_LOCAL
	ufw reset
	apt-get remove fail2ban ufw -y
	apt-get autoremove --purge -y
	apt-get clean -y
fi

rm -r $PATH_INITPI_BACKUPS

curl https://spiffindustries.com/rpi4/?status=1
