#!/bin/bash

#CHANGE USER PASSSWORD

#PARSE INPUTS
if [[ -n "$1" ]] && [[ -n "$2" ]]
then
	NEW_USER="$1"
	NEW_PASSWORD="$2"
else
	printf "New password: need username and password as arguments\n"
	exit 1
fi

printf "$NEW_USER":"$NEW_PASSWORD" | chpasswd
