#!/bin/bash

#FIX ANY INSTALLATION PROBLEMS

#TRY TO CONNECT TO INTERNET
timelimit=60
counter=0
timeout=0
printf "Attempting internet connection (timeout after 60 seconds)...\n"
while [[ "$(curl -s --max-time 2 -I http://raspberrypi.org | sed 's/^[^ ]*  *\([0-9]\).*/\1/; 1q')" -ne 3 ]]
do
sleep 1
let counter++
if [[ "$counter" -ge "$timelimit" ]]
then
    timeout=1
    break
fi
done


#UPDATE [POTENTIALLY BROKEN] SYSTEM IF CONNECTED TO INTERNET (TRY A MAX OF 5 TIMES)
if [[ "$timeout" -eq 1 ]]
then
    printf "Timeout attempting to reach internet\n"
else
	trylimit=5
	tries=0
	while [[ "$tries" -lt "$trylimit" ]]
	do
		if apt-get update --fix-missing -y && apt-get -f install -y && apt-get --fix-broken install -y && apt-get autoremove --purge -y && apt-get clean -y
		then
			break
		else
			printf "Error occured during update, re-trying\n"
			((tries++))
			sleep 1
		fi
	done
fi

if [[ "$tries" -eq "$trylimit" ]]
then
	printf "Unable to complete upgrade after trying five times\n"
	exit 1
else
	printf "Success!\n"
	exit 0
fi
