#!/bin/bash

#UPDATE SYSTEM
#https://www.raspberrypi.org/documentation/raspbian/updating.md

apt-get update -y
apt-get full-upgrade -y
apt-get autoremove --purge -y #not really necessary
apt-get clean -y
