#!/bin/bash

#https://www.google.com/amp/s/linoxide.com/linux-command/set-time-date-timezone-ubuntu-linux/amp/

#PARSE ARGUMENTS
if [[ -n "$1" ]]
then
	NEW_TIMEZONE="$1"
else
	printf "Timezone setup: need timezone as argument\n"
	exit 1
fi

#SET TIMEZONE
timedatectl set-timezone "$NEW_TIMEZONE"
