#!/bin/bash

#SET TIME ZONE
#https://www.google.com/amp/s/linoxide.com/linux-command/set-time-date-timezone-ubuntu-linux/amp/

#PARSE ARGUMENTS
if [[ -n "$1" ]]
then
	NEW_TIMEZONE="$1"
else
	echo "Timezone setup: need timezone as argument"
	exit 1
fi

timedatectl set-timezone $NEW_TIMEZONE
