#!/bin/bash

#https://www.raspberrypi.org/documentation/configuration/wireless/wireless-cli.md

#SET PATHS
PATH_WPA_CONF="/etc/wpa_supplicant/wpa_supplicant.conf"

#PARSE ARGUMENTS
if [[ -n "$1" ]]
then
	NEW_SSID="$1"
else
	printf "WIFI setup: need at least an SSID as an argument\n"
	exit 1
fi

#CONFIGURE WIFI
if [[ -n "$2" ]]
then
	NEW_WPA="$2"
	wpa_passphrase "$NEW_SSID" "$NEW_WPA" | tee -a "$PATH_WPA_CONF" > /dev/null
	# CHECK IF NETWORK IS HIDDEN (THIRD ARGUMENT IS "HIDDEN" BUT REALLY ANY STRING)
	#if [[ -n "$3" ]]
	#then
	#	sed -i '/#psk=/c\\tscan_ssid=1' "$PATH_WPA_CONF"
	#else
	sed -i "/${NEW_WPA}/d" "$PATH_WPA_CONF"
	#fi
else
	printf "network={\n\tssid=\"${NEW_SSID}\"\n\tkey_mgmt=NONE\n}\n" >> "$PATH_WPA_CONF"
fi

#Add country code
#https://www.raspberrypi.org/documentation/configuration/wireless/wireless-cli.md
sed -i '/^country=/d' "$PATH_WPA_CONF"
sed -i '/^update_config/a country=US' "$PATH_WPA_CONF"
wpa_cli -i wlan0 reconfigure
